class Story < ActiveRecord::Base

  def begin_story
  end

  def use_powers
    #random power using current character
    #update story move table
  end

  def use_friends
    #random friends team using current character
    #update story move table
  end

  def user_powers
    #random power that the user input
    #update story move table
  end

  def comp_reaction
    #random reaction by the computer
    #update story move table
  end

  def comp_story
    #random power, friends or enemies story generated by computer character
    #update story move table
  end

  def outcome
  end

end