class Story < ActiveRecord::Base

  before_create :zero_moves

  def add_char_damage!
    self.char_one_damage += 1
    self.save!
  end

  def add_opponent_damage!
    self.char_two_damage += 1
    self.save!
  end

  def winner?
    if self.char_one_damage == 5
      self.character_two
    elsif self.char_two_damage == 5
      self.character_one
    else
      "none"
    end
  end

  # def call_powers
  #   #random power using current character
  #   #update story move table
  # end

  # def call_friends
  #   #random friends team using current character
  #   #update story move table
  # end

  # def user_powers
  #   #random power that the user input
  #   #update story move table
  # end

  # def comp_reaction
  #   #random reaction by the computer
  #   #update story move table
  # end

  # def comp_story
  #   #random power, friends or enemies story generated by computer character
  #   #update story move table
  # end

  # def outcome
  # end

##before create##

  def zero_moves
    self.char_one_damage = 0
    self.char_two_damage = 0
  end


end